/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RushCheckinRouteImport } from './routes/rush-checkin'
import { Route as RushRouteImport } from './routes/rush'
import { Route as ConsultingRouteImport } from './routes/consulting'
import { Route as BrothersRouteImport } from './routes/brothers'
import { Route as ApplicationRouteImport } from './routes/application'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRushEvalsRouteImport } from './routes/admin.rush-evals'
import { Route as AdminMyEvalsRouteImport } from './routes/admin.my-evals'
import { Route as AdminInvitationalEvalsRouteImport } from './routes/admin.invitational-evals'
import { Route as AdminInterviewsRouteImport } from './routes/admin.interviews'
import { Route as AdminEvalsRouteImport } from './routes/admin.evals'
import { Route as AdminDeliberateRouteImport } from './routes/admin.deliberate'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'

const RushCheckinRoute = RushCheckinRouteImport.update({
  id: '/rush-checkin',
  path: '/rush-checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const RushRoute = RushRouteImport.update({
  id: '/rush',
  path: '/rush',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const BrothersRoute = BrothersRouteImport.update({
  id: '/brothers',
  path: '/brothers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationRoute = ApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRushEvalsRoute = AdminRushEvalsRouteImport.update({
  id: '/admin/rush-evals',
  path: '/admin/rush-evals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMyEvalsRoute = AdminMyEvalsRouteImport.update({
  id: '/admin/my-evals',
  path: '/admin/my-evals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvitationalEvalsRoute = AdminInvitationalEvalsRouteImport.update({
  id: '/admin/invitational-evals',
  path: '/admin/invitational-evals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInterviewsRoute = AdminInterviewsRouteImport.update({
  id: '/admin/interviews',
  path: '/admin/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEvalsRoute = AdminEvalsRouteImport.update({
  id: '/admin/evals',
  path: '/admin/evals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeliberateRoute = AdminDeliberateRouteImport.update({
  id: '/admin/deliberate',
  path: '/admin/deliberate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alumni': typeof AlumniRoute
  '/application': typeof ApplicationRoute
  '/brothers': typeof BrothersRoute
  '/consulting': typeof ConsultingRoute
  '/rush': typeof RushRoute
  '/rush-checkin': typeof RushCheckinRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/deliberate': typeof AdminDeliberateRoute
  '/admin/evals': typeof AdminEvalsRoute
  '/admin/interviews': typeof AdminInterviewsRoute
  '/admin/invitational-evals': typeof AdminInvitationalEvalsRoute
  '/admin/my-evals': typeof AdminMyEvalsRoute
  '/admin/rush-evals': typeof AdminRushEvalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alumni': typeof AlumniRoute
  '/application': typeof ApplicationRoute
  '/brothers': typeof BrothersRoute
  '/consulting': typeof ConsultingRoute
  '/rush': typeof RushRoute
  '/rush-checkin': typeof RushCheckinRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/deliberate': typeof AdminDeliberateRoute
  '/admin/evals': typeof AdminEvalsRoute
  '/admin/interviews': typeof AdminInterviewsRoute
  '/admin/invitational-evals': typeof AdminInvitationalEvalsRoute
  '/admin/my-evals': typeof AdminMyEvalsRoute
  '/admin/rush-evals': typeof AdminRushEvalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alumni': typeof AlumniRoute
  '/application': typeof ApplicationRoute
  '/brothers': typeof BrothersRoute
  '/consulting': typeof ConsultingRoute
  '/rush': typeof RushRoute
  '/rush-checkin': typeof RushCheckinRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/deliberate': typeof AdminDeliberateRoute
  '/admin/evals': typeof AdminEvalsRoute
  '/admin/interviews': typeof AdminInterviewsRoute
  '/admin/invitational-evals': typeof AdminInvitationalEvalsRoute
  '/admin/my-evals': typeof AdminMyEvalsRoute
  '/admin/rush-evals': typeof AdminRushEvalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alumni'
    | '/application'
    | '/brothers'
    | '/consulting'
    | '/rush'
    | '/rush-checkin'
    | '/admin/applications'
    | '/admin/deliberate'
    | '/admin/evals'
    | '/admin/interviews'
    | '/admin/invitational-evals'
    | '/admin/my-evals'
    | '/admin/rush-evals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alumni'
    | '/application'
    | '/brothers'
    | '/consulting'
    | '/rush'
    | '/rush-checkin'
    | '/admin/applications'
    | '/admin/deliberate'
    | '/admin/evals'
    | '/admin/interviews'
    | '/admin/invitational-evals'
    | '/admin/my-evals'
    | '/admin/rush-evals'
  id:
    | '__root__'
    | '/'
    | '/alumni'
    | '/application'
    | '/brothers'
    | '/consulting'
    | '/rush'
    | '/rush-checkin'
    | '/admin/applications'
    | '/admin/deliberate'
    | '/admin/evals'
    | '/admin/interviews'
    | '/admin/invitational-evals'
    | '/admin/my-evals'
    | '/admin/rush-evals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlumniRoute: typeof AlumniRoute
  ApplicationRoute: typeof ApplicationRoute
  BrothersRoute: typeof BrothersRoute
  ConsultingRoute: typeof ConsultingRoute
  RushRoute: typeof RushRoute
  RushCheckinRoute: typeof RushCheckinRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminDeliberateRoute: typeof AdminDeliberateRoute
  AdminEvalsRoute: typeof AdminEvalsRoute
  AdminInterviewsRoute: typeof AdminInterviewsRoute
  AdminInvitationalEvalsRoute: typeof AdminInvitationalEvalsRoute
  AdminMyEvalsRoute: typeof AdminMyEvalsRoute
  AdminRushEvalsRoute: typeof AdminRushEvalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rush-checkin': {
      id: '/rush-checkin'
      path: '/rush-checkin'
      fullPath: '/rush-checkin'
      preLoaderRoute: typeof RushCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rush': {
      id: '/rush'
      path: '/rush'
      fullPath: '/rush'
      preLoaderRoute: typeof RushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brothers': {
      id: '/brothers'
      path: '/brothers'
      fullPath: '/brothers'
      preLoaderRoute: typeof BrothersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application': {
      id: '/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof ApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rush-evals': {
      id: '/admin/rush-evals'
      path: '/admin/rush-evals'
      fullPath: '/admin/rush-evals'
      preLoaderRoute: typeof AdminRushEvalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/my-evals': {
      id: '/admin/my-evals'
      path: '/admin/my-evals'
      fullPath: '/admin/my-evals'
      preLoaderRoute: typeof AdminMyEvalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invitational-evals': {
      id: '/admin/invitational-evals'
      path: '/admin/invitational-evals'
      fullPath: '/admin/invitational-evals'
      preLoaderRoute: typeof AdminInvitationalEvalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/interviews': {
      id: '/admin/interviews'
      path: '/admin/interviews'
      fullPath: '/admin/interviews'
      preLoaderRoute: typeof AdminInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/evals': {
      id: '/admin/evals'
      path: '/admin/evals'
      fullPath: '/admin/evals'
      preLoaderRoute: typeof AdminEvalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deliberate': {
      id: '/admin/deliberate'
      path: '/admin/deliberate'
      fullPath: '/admin/deliberate'
      preLoaderRoute: typeof AdminDeliberateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlumniRoute: AlumniRoute,
  ApplicationRoute: ApplicationRoute,
  BrothersRoute: BrothersRoute,
  ConsultingRoute: ConsultingRoute,
  RushRoute: RushRoute,
  RushCheckinRoute: RushCheckinRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminDeliberateRoute: AdminDeliberateRoute,
  AdminEvalsRoute: AdminEvalsRoute,
  AdminInterviewsRoute: AdminInterviewsRoute,
  AdminInvitationalEvalsRoute: AdminInvitationalEvalsRoute,
  AdminMyEvalsRoute: AdminMyEvalsRoute,
  AdminRushEvalsRoute: AdminRushEvalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
